language: generic

sudo: required
services:
    - docker
    
before_install:
    - docker build -t cnoel/docker-react -f Dockerfile.dev .
    
script:
    - docker run cnoel/docker-react npm run test -- --coverage
  